"""empty message

Revision ID: 45dbdef618ba
Revises: 139ae0418d83
Create Date: 2021-02-24 19:01:35.654943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dbdef618ba'
down_revision = '139ae0418d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('school', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    # ### end Alembic commands ###
